// PulseData — данные для Пульс-Онбординга

const PULSE_EMPLOYEES = [
  // RED — high risk
  { id: 'e1', name: 'Иван Петров', role: 'Кладовщик', dept: 'Логистика', mgr: 'А.С. Иванов',
    day: 32, hireDate: '03.04.26', segment: 'mass',
    risk: 78, signal: { kind: 'red', text: '⚠️ ЗП не получил' },
    lastSurvey: { day: 30, answered: true, mood: 'bad' },
    breakdown: [
      { kind: 'red',   text: 'Зарплата не получена вовремя (день 30)', pts: 30 },
      { kind: 'red',   text: 'Оценка руководителя: 2/5',                pts: 25 },
      { kind: 'yellow',text: 'Удовлетворённость: 2/5',                  pts: 20 },
      { kind: 'green', text: 'Ответил на оба опроса',                   pts: 0 },
      { kind: 'green', text: 'eNPS пока не замерен (день 90 не наступил)', pts: 0 },
    ],
    base: 3,
    surveys: [
      { day: 7,  sentDate: '12.04.26 10:00', answeredDate: '12.04.26 10:23', responseTime: '23 мин',
        rate: 3.4, mood: '🙂', clarity: '4/5', summary: 'всё понятно, зарплата позже', critical: false },
      { day: 30, sentDate: '05.05.26 10:00', answeredDate: '05.05.26 14:08', responseTime: '4 ч',
        rate: 2.4, mood: '😞', summary: 'ЗП не получил · руководитель 2/5', critical: true },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '04.07.26' },
    ],
    quotes: [
      { text: 'Обещали зарплату 1-го, сегодня уже 5-е, никто ничего не объясняет.', date: '05.05.26', tags: ['зарплата'], crit: true },
      { text: 'С коллегами норм, мастер кричит на смене, не комфортно.', date: '05.05.26', tags: ['руководитель'], warn: true },
    ],
    alerts: [
      { date: '05.05 14:08', type: 'crit', text: 'Не получил ЗП на день 30', status: 'open' },
      { date: '02.05 11:30', type: 'med',  text: 'Оценил руководителя на 2/5', status: 'work', by: 'Анна С.' },
    ],
    hrLog: [
      { date: '05.05.26 14:30', text: 'Эскалировал в бухгалтерию — должны зачислить ЗП до конца дня.', tag: 'эскалация', author: 'Анна С.' },
    ],
  },
  { id: 'e2', name: 'Мария Орлова', role: 'Оператор кол-центра', dept: 'Поддержка', mgr: 'И.В. Левин',
    day: 18, hireDate: '15.04.26', segment: 'mass',
    risk: 72, signal: { kind: 'red', text: '⚠️ Триггер «увольняюсь»' },
    lastSurvey: { day: 7, answered: true, mood: 'bad' },
    surveys: [
      { day: 7, sentDate: '22.04.26 10:00', answeredDate: '22.04.26 11:34', responseTime: '1.5 ч',
        rate: 2.6, mood: '🙁', summary: 'график и ожидания не совпали', critical: true },
      { day: 30, sentDate: null, answeredDate: null, scheduled: '15.05.26' },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '14.07.26' },
    ],
    quotes: [
      { text: 'Так не могу больше, увольняюсь, графики какие-то странные, обещали одно — на деле другое.', date: '03.05.26', tags: ['график', 'увольнение'], crit: true },
    ],
    hrLog: [],
  },
  { id: 'e3', name: 'Денис Соколов', role: 'Грузчик', dept: 'Склад', mgr: 'А.С. Иванов',
    day: 6, hireDate: '27.04.26', segment: 'mass',
    risk: 65, signal: { kind: 'red', text: '⚠️ Не отвечает 7 дней' },
    lastSurvey: { day: 7, answered: false, mood: null },
  },

  // YELLOW — medium
  { id: 'e4', name: 'Анна Смирнова', role: 'Frontend-разработчик', dept: 'IT', mgr: 'П.К. Сидоров',
    day: 14, hireDate: '19.04.26', segment: 'office',
    risk: 45, signal: null,
    lastSurvey: { day: 7, answered: true, mood: 'mid' },
    breakdown: [
      { kind: 'yellow',text: 'Оценка руководителя: 2/5',     pts: 25 },
      { kind: 'green', text: 'Зарплата вовремя',              pts: 0 },
      { kind: 'green', text: 'Ответил на опрос дня 7',        pts: 0 },
      { kind: 'green', text: 'Удовлетворённость: 4/5',        pts: 0 },
      { kind: 'green', text: 'Триггер-слов нет',              pts: 0 },
    ],
    base: 20,
    surveys: [
      { day: 7,  sentDate: '26.04.26 10:00', answeredDate: '26.04.26 11:42', responseTime: '1.5 ч',
        rate: 3.2, mood: '🙂', summary: 'руководителя оценил на 2/5', critical: false },
      { day: 30, sentDate: null, answeredDate: null, scheduled: '19.05.26' },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '18.07.26' },
    ],
    quotes: [
      { text: 'Задачи интересные, но руководитель почти не отвечает на вопросы.', date: '26.04.26', tags: ['руководитель'], warn: true },
    ],
    alerts: [
      { date: '02.05 11:30', type: 'med', text: 'Оценила руководителя на 2/5', status: 'open' },
    ],
    hrLog: [],
  },
  { id: 'e5', name: 'Мария Кузнецова', role: 'Продавец', dept: 'Ритейл', mgr: 'Д.Н. Орлов',
    day: 8, hireDate: '25.04.26', segment: 'mass',
    risk: 52, signal: { kind: 'warn', text: 'Не ответила на опрос' },
    lastSurvey: { day: 7, answered: false, mood: null },
  },
  { id: 'e6', name: 'Олег Кравцов', role: 'Backend-разработчик', dept: 'IT', mgr: 'П.К. Сидоров',
    day: 22, hireDate: '11.04.26', segment: 'office',
    risk: 41, signal: null,
    lastSurvey: { day: 7, answered: true, mood: 'mid' },
    surveys: [
      { day: 7, sentDate: '18.04.26 10:00', answeredDate: '18.04.26 13:22', responseTime: '3 ч',
        rate: 3.6, mood: '😐', summary: 'роль понятна, инструменты приходят медленно', critical: false },
      { day: 30, sentDate: null, answeredDate: null, scheduled: '11.05.26' },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '10.07.26' },
    ],
    quotes: [
      { text: 'Ноутбук жду вторую неделю, пишу со старого личного.', date: '18.04.26', tags: ['онбординг'] },
    ],
    hrLog: [],
  },
  { id: 'e7', name: 'Светлана Беляева', role: 'Дизайнер', dept: 'Маркетинг', mgr: 'К.А. Зимина',
    day: 47, hireDate: '17.03.26', segment: 'office',
    risk: 38, signal: null,
    lastSurvey: { day: 30, answered: true, mood: 'mid' },
    surveys: [
      { day: 7, sentDate: '24.03.26 10:00', answeredDate: '24.03.26 12:08', responseTime: '2 ч',
        rate: 4.0, mood: '🙂', summary: 'всё понятно, команда дружелюбная', critical: false },
      { day: 30, sentDate: '16.04.26 10:00', answeredDate: '16.04.26 18:45', responseTime: '8.5 ч',
        rate: 3.4, mood: '😐', summary: 'брифы размытые, переделываю по 3-4 раза', critical: false },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '15.06.26' },
    ],
    quotes: [
      { text: 'Брифы приходят без контекста, потом всё переделываем.', date: '16.04.26', tags: ['процессы'], warn: true },
    ],
    hrLog: [],
  },
  { id: 'e8', name: 'Артём Лебедев', role: 'Курьер', dept: 'Доставка', mgr: 'А.С. Иванов',
    day: 11, hireDate: '22.04.26', segment: 'mass',
    risk: 36, signal: null,
    lastSurvey: { day: 7, answered: true, mood: 'mid' },
    surveys: [
      { day: 7, sentDate: '29.04.26 10:00', answeredDate: '29.04.26 14:50', responseTime: '5 ч',
        rate: 3.2, mood: '😐', summary: 'маршруты длинные, связь с диспетчером ок', critical: false },
      { day: 30, sentDate: null, answeredDate: null, scheduled: '22.05.26' },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '21.07.26' },
    ],
    quotes: [],
    hrLog: [],
  },

  // GREEN — ok
  { id: 'e9', name: 'Сергей Волков', role: 'HR-менеджер', dept: 'HR', mgr: 'О.М. Петрова',
    day: 65, hireDate: '27.02.26', segment: 'office',
    risk: 12, signal: null,
    lastSurvey: { day: 30, answered: true, mood: 'good' },
    surveys: [
      { day: 7, sentDate: '06.03.26 10:00', answeredDate: '06.03.26 14:30', responseTime: '4.5 ч', rate: 4.2, mood: '🙂', summary: 'влился быстро, рекрутинг-процессы понятны', critical: false },
      { day: 30, sentDate: '29.03.26 10:00', answeredDate: '29.03.26 16:20', responseTime: '6 ч', rate: 4.6, mood: '😀', summary: 'нагрузка ок, команда отзывчивая', critical: false },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [
      { text: 'Хочется больше структуры в онбординге кандидатов, но это мой запрос как HR.', date: '29.03.26', tags: ['онбординг'] },
    ],
    hrLog: [],
  },
  { id: 'e10', name: 'Юлия Ефимова', role: 'Аналитик', dept: 'Аналитика', mgr: 'Д.Е. Куликов',
    day: 73, hireDate: '19.02.26', segment: 'office',
    risk: 8, signal: null,
    lastSurvey: { day: 30, answered: true, mood: 'good' },
    surveys: [
      { day: 7, sentDate: '26.02.26 10:00', answeredDate: '26.02.26 14:30', responseTime: '4.5 ч', rate: 4, mood: '🙂', summary: 'вошла в задачи, дашборды разобрала', critical: false },
      { day: 30, sentDate: '21.03.26 10:00', answeredDate: '21.03.26 16:20', responseTime: '6 ч', rate: 4.4, mood: '😀', summary: 'BI-инструменты ок, доступы выданы вовремя', critical: false },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [],
    hrLog: [],
  },
  { id: 'e11', name: 'Михаил Карпов', role: 'DevOps', dept: 'IT', mgr: 'П.К. Сидоров',
    day: 58, hireDate: '06.03.26', segment: 'office',
    risk: 18, signal: null,
    lastSurvey: { day: 30, answered: true, mood: 'good' },
    surveys: [
      { day: 7, sentDate: '13.03.26 10:00', answeredDate: '13.03.26 14:30', responseTime: '4.5 ч', rate: 4, mood: '🙂', summary: 'инфраструктура понятна, прод-доступ ждёт', critical: false },
      { day: 30, sentDate: '05.04.26 10:00', answeredDate: '05.04.26 16:20', responseTime: '6 ч', rate: 4.5, mood: '😀', summary: 'релизный процесс налажен, пейджер настроен', critical: false },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [],
    hrLog: [],
  },
  { id: 'e12', name: 'Вероника Громова', role: 'Маркетолог', dept: 'Маркетинг', mgr: 'К.А. Зимина',
    day: 41, hireDate: '23.03.26', segment: 'office',
    risk: 15, signal: null,
    lastSurvey: { day: 30, answered: true, mood: 'good' },
    surveys: [
      { day: 7, sentDate: '30.03.26 10:00', answeredDate: '30.03.26 14:30', responseTime: '4.5 ч', rate: 4.1, mood: '🙂', summary: 'кампании понятны, креативы согласованы', critical: false },
      { day: 30, sentDate: '22.04.26 10:00', answeredDate: '22.04.26 16:20', responseTime: '6 ч', rate: 4.3, mood: '😀', summary: 'результаты A/B тестов хорошие, команда поддерживает', critical: false },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [],
    hrLog: [],
  },
  { id: 'e13', name: 'Дмитрий Усов', role: 'Менеджер по продажам', dept: 'Продажи', mgr: 'И.В. Левин',
    day: 25, hireDate: '08.04.26', segment: 'office',
    risk: 22, signal: null,
    lastSurvey: { day: 7, answered: true, mood: 'good' },
    surveys: [
      { day: 7, sentDate: '15.04.26 10:00', answeredDate: '15.04.26 14:30', responseTime: '4.5 ч', rate: 4, mood: '🙂', summary: 'продукт понятен, скрипты выучил', critical: false },
      { day: 30, sentDate: null, answeredDate: null, scheduled: '—' },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [
      { text: 'Не хватает прозрачности по бонусной части — спрашиваю у руководителя.', date: '15.04.26', tags: ['онбординг'] },
    ],
    hrLog: [],
  },
  { id: 'e14', name: 'Алёна Тихонова', role: 'Кассир', dept: 'Ритейл', mgr: 'Д.Н. Орлов',
    day: 52, hireDate: '12.03.26', segment: 'mass',
    risk: 14, signal: null,
    lastSurvey: { day: 30, answered: true, mood: 'good' },
    surveys: [
      { day: 7, sentDate: '19.03.26 10:00', answeredDate: '19.03.26 14:30', responseTime: '4.5 ч', rate: 4, mood: '🙂', summary: 'кассу освоила, очереди не пугают', critical: false },
      { day: 30, sentDate: '11.04.26 10:00', answeredDate: '11.04.26 16:20', responseTime: '6 ч', rate: 4.5, mood: '😀', summary: 'смены удобные, коллеги помогают', critical: false },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [],
    hrLog: [],
  },
  { id: 'e15', name: 'Никита Васильев', role: 'Сборщик заказов', dept: 'Склад', mgr: 'А.С. Иванов',
    day: 30, hireDate: '03.04.26', segment: 'mass',
    risk: 25, signal: null,
    lastSurvey: { day: 30, answered: true, mood: 'mid' },
    surveys: [
      { day: 7, sentDate: '10.04.26 10:00', answeredDate: '10.04.26 14:30', responseTime: '4.5 ч', rate: 3.8, mood: '🙂', summary: 'комплектация понятна, темп норм', critical: false },
      { day: 30, sentDate: '03.05.26 10:00', answeredDate: '03.05.26 16:20', responseTime: '6 ч', rate: 3.4, mood: '😐', summary: 'хочется больше техники, ноги устают', critical: false },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [
      { text: 'Хорошо бы больше тележек на смену — иногда стоят очереди.', date: '03.05.26', tags: ['онбординг'] },
    ],
    hrLog: [],
  },
  { id: 'e16', name: 'Ксения Жукова', role: 'Бухгалтер', dept: 'Финансы', mgr: 'Е.В. Тарасова',
    day: 80, hireDate: '12.02.26', segment: 'office',
    risk: 6, signal: null,
    lastSurvey: { day: 30, answered: true, mood: 'good' },
    surveys: [
      { day: 7, sentDate: '19.02.26 10:00', answeredDate: '19.02.26 14:30', responseTime: '4.5 ч', rate: 4.5, mood: '😀', summary: '1С-Бухгалтерия настроена, доступы есть', critical: false },
      { day: 30, sentDate: '14.03.26 10:00', answeredDate: '14.03.26 16:20', responseTime: '6 ч', rate: 4.7, mood: '😀', summary: 'отчётный период прошёл без сюрпризов', critical: false },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [],
    hrLog: [],
  },
  { id: 'e17', name: 'Тимур Багаев', role: 'QA-инженер', dept: 'IT', mgr: 'П.К. Сидоров',
    day: 19, hireDate: '14.04.26', segment: 'office',
    risk: 28, signal: null,
    lastSurvey: { day: 7, answered: true, mood: 'mid' },
    surveys: [
      { day: 7, sentDate: '21.04.26 10:00', answeredDate: '21.04.26 14:30', responseTime: '4.5 ч', rate: 3.8, mood: '🙂', summary: 'тест-кейсы написал, релиз-цикл понятен', critical: false },
      { day: 30, sentDate: null, answeredDate: null, scheduled: '—' },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [
      { text: 'Хочется больше времени на регрессы перед релизом.', date: '21.04.26', tags: ['онбординг'] },
    ],
    hrLog: [],
  },
  { id: 'e18', name: 'Полина Семёнова', role: 'Продакт-менеджер', dept: 'IT', mgr: 'Д.Е. Куликов',
    day: 67, hireDate: '25.02.26', segment: 'office',
    risk: 11, signal: null,
    lastSurvey: { day: 30, answered: true, mood: 'good' },
    surveys: [
      { day: 7, sentDate: '04.03.26 10:00', answeredDate: '04.03.26 14:30', responseTime: '4.5 ч', rate: 4.2, mood: '🙂', summary: 'продукт-команда познакомила с roadmap', critical: false },
      { day: 30, sentDate: '27.03.26 10:00', answeredDate: '27.03.26 16:20', responseTime: '6 ч', rate: 4.6, mood: '😀', summary: 'roadmap понятен, метрики настроены', critical: false },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [],
    hrLog: [],
  },
  { id: 'e19', name: 'Роман Петренко', role: 'Логист', dept: 'Логистика', mgr: 'А.С. Иванов',
    day: 36, hireDate: '30.03.26', segment: 'office',
    risk: 24, signal: null,
    lastSurvey: { day: 30, answered: true, mood: 'good' },
    surveys: [
      { day: 7, sentDate: '06.04.26 10:00', answeredDate: '06.04.26 14:30', responseTime: '4.5 ч', rate: 3.9, mood: '🙂', summary: 'маршруты освоил, авто получил', critical: false },
      { day: 30, sentDate: '29.04.26 10:00', answeredDate: '29.04.26 16:20', responseTime: '6 ч', rate: 4.2, mood: '😀', summary: 'график устраивает, заказы стабильные', critical: false },
      { day: 90, sentDate: null, answeredDate: null, scheduled: '—' },
    ],
    quotes: [],
    hrLog: [],
  },
  { id: 'e20', name: 'Лиза Ковалёва', role: 'Стажёр-рекрутер', dept: 'HR', mgr: 'О.М. Петрова',
    day: 4, hireDate: '29.04.26', segment: 'office',
    risk: 5, signal: null,
    lastSurvey: { day: 7, answered: false, mood: null },
  },
];

const PULSE_ALERTS = [
  { id: 'a1', level: 'crit', empId: 'e1', empName: 'Иван Петров', empRole: 'Кладовщик · Логистика',
    text: 'Не получил ЗП на день 30', quote: '«Обещали зарплату 1-го, сегодня уже 5-е, никто ничего не объясняет»',
    date: '05.05 14:08', sla: { state: 'warn', text: '⏰ 2 ч до дедлайна' },
    status: 'open', by: null,
    playbook: [
      'Свяжитесь с сотрудником в течение 4 часов — дайте знать, что HR в курсе.',
      'Эскалируйте в бухгалтерию: уточните, в чём задержка и когда поступит ЗП.',
      'Сообщите сотруднику конкретную дату и время выплаты письмом.',
      'После закрытия проблемы — назначьте follow-up через 7 дней.',
    ],
  },
  { id: 'a2', level: 'crit', empId: 'e2', empName: 'Мария Орлова', empRole: 'Оператор кол-центра · Поддержка',
    text: 'Триггер-слово «увольняюсь» в open-text', quote: '«Так не могу больше, увольняюсь, графики какие-то странные, обещали одно — на деле другое»',
    date: '03.05 09:15', sla: { state: 'ok', text: '✓ В срок' },
    status: 'work', by: 'Анна С.',
    playbook: [
      'Свяжитесь сегодня лично — узнайте, в чём конкретно претензия к графику.',
      'Не маршрутизируйте на руководителя автоматически — сначала разговор HR.',
      'Если претензии обоснованы — обсудите альтернативный график или ротацию.',
      'Зафиксируйте договорённости в журнале действий, follow-up через 7 дней.',
    ],
  },
  { id: 'a3', level: 'med', empId: 'e4', empName: 'Анна Смирнова', empRole: 'Frontend-разработчик · IT',
    text: 'Оценила руководителя на 2/5', quote: '«Задачи интересные, но руководитель почти не отвечает на вопросы»',
    date: '02.05 11:30', sla: { state: 'warn', text: '⏰ 22 ч до дедлайна' },
    status: 'open', by: null,
    playbook: [
      'Запланируйте 1-on-1 stay-interview в течение 48 часов.',
      'Шаблон вопросов: что нравится / что мешает / запрос к HR / что нужно от руководителя.',
      'НЕ передавайте оценку прямому руководителю — маршрут через HRBP.',
      'После встречи — назначьте follow-up через 7 дней.',
    ],
  },
  { id: 'a4', level: 'med', empId: 'e5', empName: 'Мария Кузнецова', empRole: 'Продавец · Ритейл',
    text: 'Не ответила на опрос за 48 часов',
    date: '02.05 10:01', sla: { state: 'ok', text: '✓ В срок' },
    status: 'open', by: null,
  },
  { id: 'a5', level: 'med', empId: 'e3', empName: 'Денис Соколов', empRole: 'Грузчик · Склад',
    text: 'Не ответил на 1-й опрос (день 7)',
    date: '04.05 10:01', sla: { state: 'late', text: '⏰ Просрочен 12 ч' },
    status: 'open', by: null,
  },
];

const PULSE_SURVEYS = [
  {
    id: 's7', day: 7, name: 'Реальность vs ожидания', enabled: true,
    duration: '~60 секунд', responseRate: 84,
    questions: [
      { id: 'q1', text: 'Как ты себя чувствуешь после первой недели?', goal: 'общее самочувствие',
        scale: 'emoji5', enabled: true },
      { id: 'q2', text: 'Понятно ли, что от тебя ждут на этой неделе?', goal: 'role clarity',
        scale: 'num5', enabled: true },
      { id: 'q3', text: 'Получил(а) всё необходимое для работы?', goal: 'compliance / онбординг',
        scale: 'binary4', enabled: true,
        options: ['Да', 'Скорее да', 'Скорее нет', 'Нет'] },
      { id: 'q4', text: 'Есть ли человек, к которому можно подойти с вопросом?', goal: 'connection',
        scale: 'binary', enabled: true },
      { id: 'q5', text: 'Понимаешь ли, как твоя работа связана с целями команды/продукта?',
        goal: 'meaning · смысл работы', scale: 'num5', enabled: true },
      { id: 'q6', text: 'Что сделало бы твою первую неделю лучше?',
        goal: 'open-text · триггер-слова', scale: 'text', enabled: true, optional: true },
    ],
  },
  {
    id: 's30', day: 30, name: 'Пик ухода', enabled: true,
    duration: '~90 секунд', responseRate: 72,
    questions: [
      { id: 'q1', text: 'Насколько ты доволен(на) работой за последний месяц?',
        goal: 'overall_satisfaction', scale: 'emoji5', enabled: true },
      { id: 'q2', text: 'Оцени своего руководителя по поддержке и обратной связи.',
        goal: 'manager_rating · ВАЖНО: маршрутизация при ≤2', scale: 'num5', enabled: true },
      { id: 'q3', text: 'Зарплата за прошлый месяц получена в срок и в полном размере?',
        goal: 'compliance · CRITICAL-триггер при «Нет»', scale: 'binary', enabled: true },
      { id: 'q4', text: 'Хватает ли тебе автономии в принятии решений?',
        goal: 'autonomy · самостоятельность', scale: 'num5', enabled: true },
      { id: 'q5', text: 'Что больше всего мешает работать сейчас?',
        goal: 'open-text · триггер-слова', scale: 'text', enabled: true, optional: false },
    ],
  },
  {
    id: 's90', day: 90, name: 'Решение остаться', enabled: true,
    duration: '~2 минуты', responseRate: 68,
    questions: [
      { id: 'q1', text: 'Насколько вероятно, что ты останешься в компании на следующие 6 месяцев?',
        goal: 'retention intent', scale: 'num5', enabled: true },
      { id: 'q2', text: 'eNPS: насколько вероятно, что ты порекомендуешь работу здесь другу?',
        goal: 'eNPS · 0–10', scale: 'enps', enabled: true },
      { id: 'q3', text: 'Соответствует ли работа тому, что было обещано на этапе найма?',
        goal: 'expectation match · CRITICAL при «Нет»', scale: 'num5', enabled: true },
      { id: 'q4', text: 'Видишь ли ты возможности для роста через 6–12 месяцев?',
        goal: 'growth · driver of retention', scale: 'binary4', enabled: true,
        options: ['Да, ясно', 'Скорее да', 'Скорее нет', 'Не вижу'] },
      { id: 'q5', text: 'Что бы ты изменил(а) в первые 90 дней, если бы мог(ла)?',
        goal: 'open-text · auto-tagging', scale: 'text', enabled: true, optional: false },
    ],
  },
];

const PULSE_TRIGGER_WORDS = [
  'увольняюсь', 'ухожу', 'не справляюсь', 'обманули', 'нет зарплаты',
  'штрафуют', 'ору', 'грубит', 'небезопасно', 'травма',
  'домогательство', 'дискриминация',
];

const PULSE_KPIS = {
  active: 20, activeDelta: '+3',
  high: 3,    highDelta: '+1',
  enps: 42,   enpsDelta: '+6',
  completion: 76, completionDelta: '+4',
};

Object.assign(window, {
  PULSE_EMPLOYEES, PULSE_ALERTS, PULSE_SURVEYS,
  PULSE_TRIGGER_WORDS, PULSE_KPIS,
});
