"""Add is_mock column to verifications

Revision ID: aab4f3698d75
Revises: 8d695ff4848
Create Date: 2026-05-28 15:23:00.137051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab4f3698d75'
down_revision: Union[str, None] = '8d695ff4848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('is_mock', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'is_mock')
    # ### end Alembic commands ###