"""add invites_skipped to smart_search_runs

Revision ID: cc4b24ebbfee
Revises: a5b6c7d8e9f0
Create Date: 2026-06-08 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cc4b24ebbfee'
down_revision: Union[str, None] = 'a5b6c7d8e9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'smart_search_runs',
        sa.Column('invites_skipped', sa.Boolean(), server_default=sa.text('false'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_search_runs', 'invites_skipped')
    # ### end Alembic commands ###