"""add questions to ai_evaluations

Revision ID: f1b2c3d4e5f6
Revises: e7c3a9b1d2f4
Create Date: 2026-05-29 19:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f1b2c3d4e5f6'
down_revision: Union[str, None] = 'e7c3a9b1d2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_evaluations', sa.Column('questions', postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_evaluations', 'questions')
    # ### end Alembic commands ###