"""add external_id to messages

Revision ID: f4e5d6c7a8b9
Revises: e2f3a4b5c6d7
Create Date: 2026-06-02 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e5d6c7a8b9'
down_revision: Union[str, None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.create_index('ix_messages_external_id', 'messages', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_external_id', table_name='messages')
    op.drop_column('messages', 'external_id')
    # ### end Alembic commands ###