"""add smart_search enhanced logging fields

Добавляет колонки для улучшенной отчётности умного подбора:
- scored_candidates: JSONB список всех оценённых кандидатов с полной информацией
- passed_threshold: Integer счётчик прошедших порог
- note: Text честное описание результатов без фейков
- log: JSONB лог прогресса для показа пользователю

Revision ID: g0h1j2k3l4m5
Revises: f9a8b7c6d5e4
Create Date: 2026-06-08 18:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'g0h1j2k3l4m5'
down_revision: Union[str, None] = 'f9a8b7c6d5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_search_runs', sa.Column('scored_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('smart_search_runs', sa.Column('passed_threshold', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('smart_search_runs', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('smart_search_runs', sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_search_runs', 'log')
    op.drop_column('smart_search_runs', 'note')
    op.drop_column('smart_search_runs', 'passed_threshold')
    op.drop_column('smart_search_runs', 'scored_candidates')
    # ### end Alembic commands ###