"""add_base_search_runs

Добавляет таблицу base_search_runs для истории поиска по собственной базе кандидатов.

Revision ID: k2l3m4n5o6p7
Revises: j1k2l3m4n5o6
Create Date: 2026-06-10 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'k2l3m4n5o6p7'
down_revision: Union[str, None] = 'j1k2l3m4n5o6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_search_runs',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), server_default=sa.text("'00000000-0000-0000-0000-000000000001'"), nullable=False),
    sa.Column('search_type', sa.String(length=20), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('vacancy_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('found', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('added_to_funnel', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_search_runs')
    # ### end Alembic commands ###