"""add calls tables

Revision ID: s0t1u2v3w4x5
Revises: r9s0t1u2v3w4
Create Date: 2026-06-13

"""
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 's0t1u2v3w4x5'
down_revision: Union[str, None] = 'r9s0t1u2v3w4'
branch_labels: Union[str, tuple[str, ...], None] = None
depends_on: Union[str, tuple[str, ...], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('candidate_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('external_id', sa.String(length=255), nullable=False, comment='Идентификатор звонка в Mango Office'),
        sa.Column('recording_id', sa.String(length=255), nullable=True, comment='ID записи в Mango Office'),
        sa.Column('direction', sa.String(length=20), nullable=True, comment='Направление: out/in/missed'),
        sa.Column('from_number', sa.String(length=50), nullable=True, comment='Номер звонящего'),
        sa.Column('to_number', sa.String(length=50), nullable=True, comment='Номер получателя'),
        sa.Column('duration_sec', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True, comment='Время начала звонка'),
        sa.Column('recruiter_name', sa.String(length=255), nullable=True, comment='Имя рекрутера'),
        sa.Column('transcribe_status', sa.String(length=20), server_default=sa.text("'none'"), nullable=False, comment='Статус расшифровки: none/running/done/error'),
        sa.Column('transcript', sa.Text(), nullable=True, comment='Полная расшифровка'),
        sa.Column('transcript_segments', postgresql.JSONB(), nullable=True, comment='Сегменты с таймстампами'),
        sa.Column('summary', sa.Text(), nullable=True, comment='AI-сводка звонка'),
        sa.Column('ai_hint', sa.Text(), nullable=True, comment='Совет от AI'),
        sa.Column('ai_hint_tone', sa.String(length=10), nullable=True, comment='Тон AI-совета: warn/good'),
        sa.Column('transcribe_error', sa.Text(), nullable=True, comment='Ошибка расшифровки'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('company_id', 'external_id', name='uq_calls_company_external')
    )
    op.create_index('ix_calls_candidate_id', 'calls', ['candidate_id'], unique=False)
    op.create_index('ix_calls_company_id', 'calls', ['company_id'], unique=False)

    op.create_table('call_sync_jobs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('status', sa.String(length=20), server_default=sa.text("'running'"), nullable=False, comment='Статус: running/done/error'),
        sa.Column('total', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Всего звонков в выгрузке'),
        sa.Column('matched', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Сопоставлено с кандидатами'),
        sa.Column('created', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Создано записей'),
        sa.Column('error', sa.Text(), nullable=True, comment='Ошибка выполнения'),
        sa.Column('finished_at', sa.DateTime(), nullable=True, comment='Время завершения'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_sync_jobs_company_id', 'call_sync_jobs', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_call_sync_jobs_company_id', table_name='call_sync_jobs')
    op.drop_table('call_sync_jobs')
    op.drop_index('ix_calls_company_id', table_name='calls')
    op.drop_index('ix_calls_candidate_id', table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###