// GOV-ветка — данные кадрового резерва (фиктивные, для пилота Минцифры НСО)

// Группы должностей (по ФЗ-79)
const GOV_GROUPS = ['Высшая', 'Главная', 'Ведущая', 'Старшая', 'Младшая'];

// Категории должностей
const GOV_CATEGORIES = [
  'Руководители',
  'Помощники (советники)',
  'Специалисты',
  'Обеспечивающие специалисты',
];

// Гос. органы — пилотный список (Минцифры НСО + соседи)
const GOV_ORGS = [
  { id: 'mincifry',  short: 'Минцифры НСО',  full: 'Министерство цифрового развития и связи Новосибирской области' },
  { id: 'minfin',    short: 'Минфин НСО',    full: 'Министерство финансов Новосибирской области' },
  { id: 'minecon',   short: 'Минэконом НСО', full: 'Министерство экономического развития Новосибирской области' },
  { id: 'minobr',    short: 'Минобр НСО',    full: 'Министерство образования Новосибирской области' },
  { id: 'mintrud',   short: 'Минтруд НСО',   full: 'Министерство труда и социального развития Новосибирской области' },
  { id: 'minzdrav',  short: 'Минздрав НСО',  full: 'Министерство здравоохранения Новосибирской области' },
  { id: 'mer_nsk',   short: 'Мэрия г. Новосибирска', full: 'Мэрия города Новосибирска' },
  { id: 'gubernator',short: 'Правительство НСО',    full: 'Правительство Новосибирской области' },
];

// Уровни допуска к гос. тайне
const GOV_CLEARANCES = ['Без допуска', '3 форма', '2 форма', '1 форма'];

// Классные чины — гос. гражданской службы
const GOV_RANKS = [
  'Действительный гос. советник РФ 1 класса',
  'Действительный гос. советник РФ 2 класса',
  'Гос. советник РФ 1 класса',
  'Гос. советник РФ 2 класса',
  'Гос. советник РФ 3 класса',
  'Советник гос. гражданской службы 1 класса',
  'Советник гос. гражданской службы 2 класса',
  'Референт гос. гражданской службы 1 класса',
  'Референт гос. гражданской службы 2 класса',
  'Секретарь гос. гражданской службы 1 класса',
];

// База резервистов
// readiness: 'ready' | 'needs' | 'risk'
const RESERVISTS = [
  {
    id: 'rv01', name: 'Петренко Иван Сергеевич', short: 'Петренко И.С.',
    age: 45, gender: 'm', city: 'Новосибирск',
    group: 'Ведущая', category: 'Руководители',
    govOrg: 'minfin', position: 'Начальник отдела бюджетного планирования',
    rank: 'Советник гос. гражданской службы 2 класса',
    clearance: '2 форма', clearanceDate: '14.05.2023',
    govExp: 8, totalExp: 14,
    education: 'НГУЭУ, 2003, Финансы и кредит, специалитет (с отличием)',
    eduExtra: 'РАНХиГС, 2018, проф. переподготовка «Гос. и муниципальное управление»',
    reserveSince: '15.03.2024', reserveUntil: '15.03.2027',
    decree: '№ 142-р от 15.03.2024',
    status: 'active',
    declaration: 'ok', declarationDate: '28.04.2026',
    antikor: 'clean',
    readiness: 'ready',
    phone: '+7 913 922-44-08', email: 'i.petrenko@nso.gov.ru',
    mess: ['tg'],
    matchedFor: ['mincifry-frontend-lead'],
  },
  {
    id: 'rv02', name: 'Соколова Мария Алексеевна', short: 'Соколова М.А.',
    age: 38, gender: 'f', city: 'Новосибирск',
    group: 'Ведущая', category: 'Специалисты',
    govOrg: 'mincifry', position: 'Главный специалист отдела цифровых сервисов',
    rank: 'Референт гос. гражданской службы 1 класса',
    clearance: '3 форма', clearanceDate: '12.09.2022',
    govExp: 6, totalExp: 13,
    education: 'НГТУ, 2008, Программная инженерия, магистратура',
    reserveSince: '02.07.2024', reserveUntil: '02.07.2027',
    decree: '№ 312-р от 02.07.2024',
    status: 'active',
    declaration: 'ok', declarationDate: '14.04.2026',
    antikor: 'clean',
    readiness: 'ready',
    phone: '+7 953 871-12-09', email: 'm.sokolova@nso.gov.ru',
    mess: ['tg', 'wa'],
    matchedFor: ['mincifry-frontend-lead', 'mincifry-it-arch'],
  },
  {
    id: 'rv03', name: 'Лазарев Виктор Павлович', short: 'Лазарев В.П.',
    age: 51, gender: 'm', city: 'Новосибирск',
    group: 'Главная', category: 'Руководители',
    govOrg: 'gubernator', position: 'Заместитель начальника управления',
    rank: 'Гос. советник РФ 3 класса',
    clearance: '1 форма', clearanceDate: '20.02.2020',
    govExp: 19, totalExp: 28,
    education: 'НГУ, 1996, Юриспруденция, специалитет',
    eduExtra: 'РАНХиГС, 2014, MBA «Управление в гос. секторе»',
    reserveSince: '11.11.2023', reserveUntil: '11.11.2026',
    decree: '№ 88-р от 11.11.2023',
    status: 'active',
    declaration: 'ok', declarationDate: '24.04.2026',
    antikor: 'clean',
    readiness: 'ready',
    phone: '+7 913 200-09-33', email: 'v.lazarev@nso.gov.ru',
    mess: ['tg'],
    matchedFor: [],
  },
  {
    id: 'rv04', name: 'Кравцова Анастасия Игоревна', short: 'Кравцова А.И.',
    age: 34, gender: 'f', city: 'Новосибирск',
    group: 'Старшая', category: 'Специалисты',
    govOrg: 'mincifry', position: 'Ведущий специалист отдела информационной безопасности',
    rank: 'Референт гос. гражданской службы 2 класса',
    clearance: '2 форма', clearanceDate: '03.11.2024',
    govExp: 4, totalExp: 9,
    education: 'НГТУ, 2014, Информационная безопасность, специалитет',
    reserveSince: '04.04.2025', reserveUntil: '04.04.2028',
    decree: '№ 167-р от 04.04.2025',
    status: 'active',
    declaration: 'expired', declarationDate: '12.03.2025',
    antikor: 'clean',
    readiness: 'needs',
    phone: '+7 923 117-44-22', email: 'a.kravtsova@nso.gov.ru',
    mess: ['tg', 'wa'],
    matchedFor: ['mincifry-frontend-lead'],
  },
  {
    id: 'rv05', name: 'Тимофеев Дмитрий Олегович', short: 'Тимофеев Д.О.',
    age: 42, gender: 'm', city: 'Новосибирск',
    group: 'Ведущая', category: 'Специалисты',
    govOrg: 'mincifry', position: 'Главный специалист-эксперт',
    rank: 'Советник гос. гражданской службы 1 класса',
    clearance: '2 форма', clearanceDate: '08.06.2023',
    govExp: 11, totalExp: 18,
    education: 'НГУ, 2007, Прикладная математика, специалитет',
    eduExtra: 'СибГУТИ, 2020, проф. переподготовка «Архитектура корпоративных систем»',
    reserveSince: '20.09.2023', reserveUntil: '20.09.2026',
    decree: '№ 401-р от 20.09.2023',
    status: 'active',
    declaration: 'ok', declarationDate: '02.05.2026',
    antikor: 'clean',
    readiness: 'ready',
    phone: '+7 913 504-90-15', email: 'd.timofeev@nso.gov.ru',
    mess: ['tg', 'wa'],
    matchedFor: ['mincifry-frontend-lead', 'mincifry-it-arch'],
  },
  {
    id: 'rv06', name: 'Бортникова Елена Владимировна', short: 'Бортникова Е.В.',
    age: 47, gender: 'f', city: 'Новосибирск',
    group: 'Главная', category: 'Помощники (советники)',
    govOrg: 'mer_nsk', position: 'Советник мэра по цифровизации',
    rank: 'Гос. советник РФ 3 класса',
    clearance: '3 форма', clearanceDate: '18.07.2022',
    govExp: 14, totalExp: 22,
    education: 'НГУЭУ, 2002, Государственное и муниципальное управление',
    reserveSince: '12.06.2024', reserveUntil: '12.06.2027',
    decree: '№ 254-р от 12.06.2024',
    status: 'active',
    declaration: 'ok', declarationDate: '19.04.2026',
    antikor: 'risk', antikorNote: 'Конфликт интересов: доля в ООО «Цифра-НСК» (проверяется)',
    readiness: 'risk',
    phone: '+7 905 117-22-08', email: 'e.bortnikova@novo-sibirsk.ru',
    mess: ['tg'],
    matchedFor: [],
  },
  {
    id: 'rv07', name: 'Гречко Александр Михайлович', short: 'Гречко А.М.',
    age: 39, gender: 'm', city: 'Новосибирск',
    group: 'Ведущая', category: 'Руководители',
    govOrg: 'minecon', position: 'Начальник отдела стратегического развития',
    rank: 'Советник гос. гражданской службы 2 класса',
    clearance: 'Без допуска', clearanceDate: null,
    govExp: 9, totalExp: 16,
    education: 'СПбГУ, 2008, Экономика, магистратура',
    reserveSince: '05.02.2023', reserveUntil: '05.02.2026',
    decree: '№ 51-р от 05.02.2023',
    status: 'active',
    declaration: 'ok', declarationDate: '11.04.2026',
    antikor: 'clean',
    readiness: 'risk', readinessNote: 'Срок резерва истекает через 2 месяца',
    phone: '+7 913 808-12-77', email: 'a.grechko@nso.gov.ru',
    mess: ['tg', 'max'],
    matchedFor: ['mincifry-frontend-lead'],
  },
  {
    id: 'rv08', name: 'Романова Алёна Сергеевна', short: 'Романова А.С.',
    age: 31, gender: 'f', city: 'Новосибирск',
    group: 'Старшая', category: 'Специалисты',
    govOrg: 'minobr', position: 'Ведущий специалист',
    rank: 'Референт гос. гражданской службы 2 класса',
    clearance: 'Без допуска', clearanceDate: null,
    govExp: 3, totalExp: 8,
    education: 'НГПУ, 2017, Педагогика и психология, специалитет',
    reserveSince: '17.10.2025', reserveUntil: '17.10.2028',
    decree: '№ 488-р от 17.10.2025',
    status: 'active',
    declaration: 'ok', declarationDate: '08.04.2026',
    antikor: 'clean',
    readiness: 'ready',
    phone: '+7 923 999-04-11', email: 'a.romanova@edu.nso.ru',
    mess: ['tg', 'wa'],
    matchedFor: [],
  },
  {
    id: 'rv09', name: 'Морозов Андрей Петрович', short: 'Морозов А.П.',
    age: 49, gender: 'm', city: 'Новосибирск',
    group: 'Главная', category: 'Руководители',
    govOrg: 'mintrud', position: 'Заместитель министра',
    rank: 'Гос. советник РФ 2 класса',
    clearance: '1 форма', clearanceDate: '04.03.2021',
    govExp: 17, totalExp: 25,
    education: 'НГУЭУ, 1999, Экономика труда, специалитет',
    eduExtra: 'РАНХиГС, 2012, MPA',
    reserveSince: '28.08.2023', reserveUntil: '28.08.2026',
    decree: '№ 367-р от 28.08.2023',
    status: 'active',
    declaration: 'ok', declarationDate: '03.04.2026',
    antikor: 'clean',
    readiness: 'ready',
    phone: '+7 913 552-23-44', email: 'a.morozov@mintrud.nso.ru',
    mess: ['tg'],
    matchedFor: [],
  },
  {
    id: 'rv10', name: 'Климова Дарья Антоновна', short: 'Климова Д.А.',
    age: 28, gender: 'f', city: 'Новосибирск',
    group: 'Старшая', category: 'Обеспечивающие специалисты',
    govOrg: 'mincifry', position: 'Специалист 1 разряда',
    rank: 'Секретарь гос. гражданской службы 1 класса',
    clearance: 'Без допуска', clearanceDate: null,
    govExp: 2, totalExp: 6,
    education: 'НГУ, 2019, Документоведение, бакалавриат',
    reserveSince: '14.01.2025', reserveUntil: '14.01.2028',
    decree: '№ 14-р от 14.01.2025',
    status: 'active',
    declaration: 'ok', declarationDate: '21.04.2026',
    antikor: 'clean',
    readiness: 'ready',
    phone: '+7 953 401-22-08', email: 'd.klimova@nso.gov.ru',
    mess: ['tg', 'wa'],
    matchedFor: [],
  },
  {
    id: 'rv11', name: 'Соловьёв Никита Владимирович', short: 'Соловьёв Н.В.',
    age: 36, gender: 'm', city: 'Новосибирск',
    group: 'Ведущая', category: 'Специалисты',
    govOrg: 'minzdrav', position: 'Главный специалист отдела цифровизации',
    rank: 'Советник гос. гражданской службы 2 класса',
    clearance: '3 форма', clearanceDate: '02.10.2024',
    govExp: 7, totalExp: 12,
    education: 'НГМУ, 2012, Медицинская информатика, специалитет',
    reserveSince: '03.12.2024', reserveUntil: '03.12.2027',
    decree: '№ 521-р от 03.12.2024',
    status: 'active',
    declaration: 'ok', declarationDate: '15.04.2026',
    antikor: 'clean',
    readiness: 'ready',
    phone: '+7 913 077-13-88', email: 'n.solovyev@minzdrav.nso.ru',
    mess: ['tg', 'wa', 'max'],
    matchedFor: ['mincifry-frontend-lead'],
  },
  {
    id: 'rv12', name: 'Шилов Роман Александрович', short: 'Шилов Р.А.',
    age: 33, gender: 'm', city: 'Новосибирск',
    group: 'Старшая', category: 'Специалисты',
    govOrg: 'mer_nsk', position: 'Ведущий специалист департамента ИТ',
    rank: 'Референт гос. гражданской службы 2 класса',
    clearance: 'Без допуска', clearanceDate: null,
    govExp: 5, totalExp: 9,
    education: 'НГТУ, 2015, Информационные системы, бакалавриат',
    reserveSince: '07.03.2024', reserveUntil: '07.03.2027',
    decree: '№ 109-р от 07.03.2024',
    status: 'paused', statusNote: 'Декретный отпуск супруги, работает в ином режиме',
    declaration: 'ok', declarationDate: '02.04.2026',
    antikor: 'clean',
    readiness: 'needs',
    phone: '+7 905 555-09-21', email: 'r.shilov@novo-sibirsk.ru',
    mess: ['tg'],
    matchedFor: [],
  },
];

// История назначений резервистов (хронология подбора на вакансии)
const RESERVIST_ASSIGNMENTS = {
  rv01: [
    { date: '12.02.2026', vacancy: 'Замначальника отдела ИТ-инфраструктуры', org: 'Минцифры НСО', status: 'declined',  note: 'Резервист отказался' },
    { date: '04.09.2025', vacancy: 'Руководитель проектного офиса',          org: 'Минфин НСО',   status: 'not_chosen', note: 'Выбран другой кандидат' },
  ],
  rv02: [
    { date: '20.03.2026', vacancy: 'Frontend Tech Lead',                     org: 'Минцифры НСО', status: 'in_progress', note: 'Сейчас в воронке' },
  ],
  rv03: [
    { date: '14.11.2025', vacancy: 'Зам. министра по цифровому развитию',    org: 'Минцифры НСО', status: 'appointed',   note: 'Назначен, но позже вернулся в резерв' },
  ],
  rv04: [],
  rv05: [
    { date: '11.01.2026', vacancy: 'Архитектор гос. ИС',                     org: 'Минцифры НСО', status: 'agreed',     note: 'Согласие получено' },
  ],
  rv06: [],
  rv07: [
    { date: '01.04.2026', vacancy: 'Начальник управления экономики',         org: 'Минэконом НСО', status: 'declined', note: 'Резервист отказался' },
  ],
  rv08: [],
  rv09: [],
  rv10: [],
  rv11: [
    { date: '08.03.2026', vacancy: 'Координатор цифровых проектов',          org: 'Минздрав НСО', status: 'appointed',  note: 'Назначен в марте 2026' },
  ],
  rv12: [],
};

// Помощник: рассчитать «осталось N месяцев» от строки 'DD.MM.YYYY'
function monthsLeft(dateStr) {
  const [d, m, y] = dateStr.split('.').map(Number);
  const target = new Date(y, m - 1, d);
  const now = new Date(2026, 4, 17); // май 2026 — фикс для пилота
  return Math.max(0, Math.round((target - now) / (1000 * 60 * 60 * 24 * 30.4)));
}

Object.assign(window, {
  GOV_GROUPS, GOV_CATEGORIES, GOV_ORGS, GOV_CLEARANCES, GOV_RANKS,
  RESERVISTS, RESERVIST_ASSIGNMENTS, monthsLeft,
});
